### ISSUE TITLE
can't install nova framework

### ISSUE THREAD

**Issue by balaji-s** [novaframework/nova#103]
sh -c "$(curl -fsSL https://raw.githubusercontent.com/novaframework/nova/master/tools/install.sh)"
sh -c "$(wget -O- https://raw.githubusercontent.com/novaframework/nova/master/tools/install.sh)" 
executing the above commands results in 404 not found
![Screenshot_20210418_181745](https://user-images.githubusercontent.com/22422768/115146142-c6e44100-a044-11eb-9407-0dd8cb94cb41.png)

**Comment by Taure** [comment]
Hi,

Sorry for that we are restructuring the installation parts and we have moved it now to this repo and haven't updated the homepage yet.

https://github.com/novaframework/rebar3_nova

We have started to work on rebar3 plugin so that we can add more functionality and tooling to Nova more than templating new applications.

If you want you can add this to your rebar.config file ( ~/.config/rebar3/rebar.config):
{plugins, [rebar3_nova]}.

After that you should be able to use rebar3 new nova MYAPP. It will install the plugin from hex.

**Comment by burbas** [comment]
Fixed with the new release of rebar3_nova. Added new instructions to README
