### ISSUE TITLE
Make plugins configurable with priority

### ISSUE THREAD

**Issue by burbas** [novaframework/nova#62]
It would be nice to have some sort of order for which plugins are executed. This can be implemented with a priority-value. Perhaps we can utilize https://github.com/okeuday/pqueue for this.

**Comment by Taure** [comment]
I think we need a priority mechanism, not sure if it should be a queue.

**Comment by burbas** [comment]
A priority queue is both a mechanism and data structure 😊

**Comment by Taure** [comment]
Yeah, understand that. :) It was more that I am not sure if the solution need to have a complex queue system.

Example:
```
        {plugins, [{pre_request, http, plugin_module_1, 10},
                    {post_request, http, plugin_module_1, 20},
                    {pre_request, http, plugin_module_2, 20},
                    {post_request, http, plugin_module_2, 10}
                    ]}
```
In this case we could let the nova_plugin sort on integer value what plugin should be handled first in pre / post.

So in the example above when nova handles a request it will first do pre for plugin 1 and then do it for plugin 2, For post it will do plugin 2 first and then plugin 1. Because of the values.

Depending what functionality we want to add later for plugins. But order could also be a way to prioritize what order they should be run without having a value to them.

Example:
```
        {plugins, [{pre, [{http, plugin_module_1},
                                 {http, plugin_module_2}},
                        {post, [{http, plugin_module_2},
                                   {http, plugin_module_1}]
                    ]}
```
In the end it is more what is the expected behaviour for plugins and the order they should be run.

**Comment by burbas** [comment]
Ah, I agree but this functionality is called on every request so it needs to be really fast :-). But it would be possible to achieve this with a sorter ETS table. But it takes some rewrites to achieve. 

Skickat från min iPhone

**Comment by Taure** [comment]
nova_plugin could have a global accessible ets table. In that way different handlers can access it. Should be fast enough in the beginning. Then we also could access it without getting any slow down in nova_plugin as a gen_server.

But we get the beneficial of supervision if it is own by nova_plugin and populated by the server. If something happens.

We could export features from nova_plugin that only access this table and not using the gen_server, not sure if that is a pretty way or not. Need to think about it.

Example: 
```
nova_plugin:get_ordered_pre(http).
[{http, plugin_module_1}, {http, plugin_module_2}]
nova_plugin:get_ordered_post(http).
[{http, plugin_module_2}, {http, plugin_module_1}]
```
Something like this. Where input is protocol for the requests.

**Comment by burbas** [comment]
The table is already marked as protected which means that the get-functions is accessing the ets-table directly. This is done.
But the more I think of it the more I like the priority-queue approach better since it has a very clear function to this problem. Plugins will be re-read from the sys.config if the server is killed/restarted. 

Skickat från min iPhone
