### ISSUE TITLE
Auto reload does not work with view changes

### ISSUE THREAD

**Issue by aleklisi** [novaframework/nova#67]
I've built the `my_first_nova` app and I noticed that with `rebar3 auto` it does not rebuild the page when any changes were made to `src/views/my_first_nova_main.dtl` file. I would expect the paged to be reloaded with the new content.
Also, it recompiles the whole project when changes are made in a controller eg. `src/controllers/my_first_nova_main_controller.erl` which takes a lot of time (~10 s) even for a small project instead of just recompiling and reading only this one module, for unknown to me reason dependencies are also recompiled.

**Comment by burbas** [comment]
Hi Alekisi. This is a known limitation and we hope to address this issue shortly. Basically the `rebar3 auto` plugin does not support DTL and as you've noticed also recompiles the whole directory.
We used `sync` before with great success (We had to tweak it a bit before) but removed it in favour for the rebar3-plugin.

This issue is one of our topmost prio since it really lower the experience using Nova.

**Comment by aleklisi** [comment]
I have a workaround for now for HTML files:
in `src/views/my_first_nova_main.dtl`

```html
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>Title</title>
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>

    <script>
        $(function () {
            $("#body").load("assets/html/body.html");
        });
    </script>
</head>

<body>
    <div id="body"></div>
</body>

</html>
```

and then you build HTML in `priv/assets/html/body.html`

**Comment by burbas** [comment]
That is a cleaver work-around :-). The more I think on this issue the more I'm for building a rebar3-plugin that we can use for various dev-tasks in Nova. Enable/disable plugins, create pages, recompile/reload code etc.
